"""Build an unpacked MV3 extension and a Chrome Web Store upload ZIP."""
import argparse
import json
import math
import pathlib
import shutil
import struct
import urllib.parse
import zlib
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEST = ROOT / 'dist' / 'cue-extension'
FILES = [
    'extension/background.js', 'extension/content.js', 'extension/extract.js',
    'extension/popup.html', 'extension/popup.css', 'extension/popup.js',
    'extension/privacy.html',
    'client/aura.js', 'client/avatar.js', 'client/badges.js', 'client/bus.js',
    'client/config.js', 'client/gaze.js', 'client/mic.js', 'client/overlay.css',
    'client/resolver.js', 'client/voice.js', 'client/product-memory.js', 'vendor/webgazer.js',
]


def server_origin(value: str) -> str:
    url = urllib.parse.urlsplit(value)
    if (url.scheme not in ('http', 'https') or not url.hostname or url.username or
            url.password or url.path not in ('', '/') or url.query or url.fragment):
        raise ValueError('Server URL must be an HTTP(S) origin with no path, query, or credentials.')
    if url.scheme == 'http' and url.hostname not in ('localhost', '127.0.0.1', '[::1]', '::1'):
        raise ValueError('A non-local Cue server must use HTTPS.')
    return f'{url.scheme}://{url.netloc}'


def icon(size: int) -> bytes:
    """Draw the Cue mark as a small antialiased PNG without build dependencies."""
    def inside(x: float, y: float) -> tuple[int, int, int, int]:
        cx = cy = size / 2
        px, py = x - cx, y - cy
        corner = size * .20
        dx = max(abs(px) - (cx - corner), 0)
        dy = max(abs(py) - (cy - corner), 0)
        if dx * dx + dy * dy > corner * corner:
            return (0, 0, 0, 0)
        radius = math.hypot(px + size * .025, py)
        angle = math.atan2(py, px + size * .025)
        stroke = size * .095
        white = abs(radius - size * .235) < stroke and abs(angle) > .53
        return (255, 255, 255, 255) if white else (47, 107, 255, 255)

    raw = bytearray()
    for y in range(size):
        raw.append(0)
        for x in range(size):
            samples = [inside(x + (i + .5) / 4, y + (j + .5) / 4)
                       for j in range(4) for i in range(4)]
            total_alpha = sum(p[3] for p in samples)
            if not total_alpha:
                raw.extend((0, 0, 0, 0))
            else:
                raw.extend(tuple(sum(p[k] * p[3] for p in samples) // total_alpha
                                 for k in range(3)) + (total_alpha // 16,))

    def chunk(kind: bytes, data: bytes) -> bytes:
        return struct.pack('!I', len(data)) + kind + data + struct.pack('!I', zlib.crc32(kind + data))

    return (b'\x89PNG\r\n\x1a\n' +
            chunk(b'IHDR', struct.pack('!2I5B', size, size, 8, 6, 0, 0, 0)) +
            chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b''))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--server-url', default='http://localhost:4173',
                        help='Cue backend origin (default: http://localhost:4173)')
    args = parser.parse_args()
    origin = server_origin(args.server_url)
    manifest = json.loads((ROOT / 'extension/manifest.json').read_text())
    manifest['host_permissions'] = [origin + '/*']
    manifest['icons'] = {str(size): f'icons/{size}.png' for size in (16, 32, 48, 128)}
    manifest['action']['default_icon'] = manifest['icons']

    if DEST.exists():
        shutil.rmtree(DEST)
    DEST.mkdir(parents=True)
    for name in FILES:
        target = DEST / name
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / name, target)
    shutil.copytree(ROOT / 'vendor/models', DEST / 'vendor/models')
    (DEST / 'extension/runtime.js').write_text(
        '// Generated by tools/build-extension.py.\n'
        f'export const SERVER_URL = {json.dumps(origin)};\n')
    (DEST / 'icons').mkdir()
    for size in (16, 32, 48, 128):
        (DEST / f'icons/{size}.png').write_bytes(icon(size))
    (DEST / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')

    archive = DEST.parent / f'cue-extension-{manifest["version"]}.zip'
    with zipfile.ZipFile(archive, 'w', compression=zipfile.ZIP_DEFLATED,
                         compresslevel=9) as out:
        for path in sorted(DEST.rglob('*')):
            if path.is_file():
                info = zipfile.ZipInfo(path.relative_to(DEST).as_posix(),
                                       date_time=(2026, 1, 1, 0, 0, 0))
                info.compress_type = zipfile.ZIP_DEFLATED
                info.external_attr = 0o644 << 16
                out.writestr(info, path.read_bytes(), compress_type=zipfile.ZIP_DEFLATED,
                             compresslevel=9)
    print(f'Unpacked extension: {DEST}')
    print(f'Upload package:     {archive}')
    print(f'Cue server:         {origin}')


if __name__ == '__main__':
    main()
